### PR TITLE
Make codespaces detection shorter

### PR DESCRIPTION
**Pull request by felipecrs**
At least until we have https://github.com/Masterminds/sprig/issues/258.

### CODE REVIEW

**Comment by twpayne** [comment]
> You're right. I would personally do this differently:

Thanks! That's a nice improvement and I've updated my template to use it.

> I know that `chezmoi` currently can not read the variables defined in `[data]` in the template time, otherwise, we could just get rid of those definitions and use `{{ .codespaces }}` instead.
> 
> Is this possible? If yes, I can open an issue for such a feature.

If I understand correctly, this is not possible. The `[data]` section is in the config file, which does not exist when the config file template is executed.

**Comment by felipecrs** [comment]
I made some changes and included an example mail address. Do you think it's a good idea?

**Comment by twpayne** [comment]
> I made some changes and included an example mail address. Do you think it's a good idea?

No :) This is a template repo for people who are just getting started with chezmoi and templates, so we should make things as easy to understand as possible, even if there are some equivalent code golf ways of achieving the same effect.

**Comment by felipecrs** [comment]
I see. What's your opinion about

```
{{- $codespaces := env "CODESPACES" | not | not -}}

sourceDir = "{{ .chezmoi.sourceDir }}"
[data]
  codespaces = {{ $codespaces }}
```

Compared to the original one?

**Comment by twpayne** [comment]
I would go with one similar to what [you suggested here](https://github.com/chezmoi/dotfiles/pull/1#issuecomment-678699265):

```
{{- $codespaces:= env "CODESPACES" | not | not -}}

[data]
  name = "Your name"
  codespaces = {{ $codespaces }}
{{- if $codespaces }}{{/* Codespaces dotfiles setup is non-interactive, so set an email address */}}
  email = "your@email.com"
{{- else }}{{/* Interactive setup, so prompt for an email address */}}
  email = "{{ promptString "email" }}"
{{- end }}
```

Reasons:

* Demonstrates several features: detecting codespaces, setting variables everywhere, setting variables depending on codespaces.
* Makes it very clear where users should add their own variables.

**Review by twpayne — APPROVED** [review]

**Comment by twpayne** [comment]
Thank you :)

**Comment by felipecrs** [comment]
> Thank you :)

No need to thanks :)!

**Pull request merged**
